import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div
      style={{
        height: "100vh",
        padding: "20px",
        backgroundColor: "#232323",
        color: "white",
      }}
    >
      {" "}
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>{" "}
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        {" "}
        This project was generated By{" "}
        <a
          href="https://www.dhiwise.com"
          style={{ color: "#87CEFA", textDecoration: "none" }}
        >
          {" "}
          Dhiwise{" "}
        </a>{" "}
        . Quickly use below links to navigate through all pages.{" "}
      </p>{" "}
      <ul style={{ listStyle: "none", padding: "0" }}>
        {" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/admanagement"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            AdManagement{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/admanagementone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            AdManagementOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/admanagementtwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            AdManagementTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/admanagementbuynow"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            AdManagementBuyNow{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/admanagementthree"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            AdManagementThree{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/admanagementfour"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            AdManagementFour{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/admanagementbuynowone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            AdManagementBuyNowOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilebuyingvehiclecomparision"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileBuyingVehicleComparision{" "}
          </Link>{" "}
        </li>
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilebuyingvehiclevaluation"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileBuyingVehicleValuation{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilebuyingvehiclevaluationone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileBuyingVehicleValuationOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilebuyingvehicledamageinquiry"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileBuyingVehicleDamageInquiry{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilebuyingmypastqueries"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileBuyingMyPastQueries{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/autoexpertise"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            AutoExpertise{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilebuyingvehiclebuyingguide"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileBuyingVehicleBuyingGuide{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilebuyingvehiclebuyingguideone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileBuyingVehicleBuyingGuideOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilebuyingvehiclebuyingguidetwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileBuyingVehicleBuyingGuideTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilebuyingvehiclebuyingguidethree"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileBuyingVehicleBuyingGuideThree{" "}
          </Link>{" "}
        </li>
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateexpertiseproperty"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateExpertiseProperty{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link to="/cart" style={{ color: "#87CEFA", textDecoration: "none" }}>
            {" "}
            Cart{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/home1"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            Home1{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/addetails"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            AdDetails{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/postanadnow"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            Postanadnow{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/postanadnowone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            PostanadnowOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/categoriescars"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            CategoriesCars{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/categoriesmobilephone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            CategoriesMobilePhone{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/maintenancerepair"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MaintenanceRepair{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/credit"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            Credit{" "}
          </Link>{" "}
        </li>
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmydelivery"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMydelivery{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmybank"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMyBank{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmydeliveryone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMydeliveryOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmydeliverytwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMydeliveryTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmypurchase"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMyPurchase{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmysales"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMySales{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmydeliverythree"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMyDeliveryThree{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmybankone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMyBankOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmyhead"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMyHead{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionswhat"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsWhat{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionswhatone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsWhatOne{" "}
          </Link>{" "}
        </li>
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionssummary"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsSummary{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmycurrent"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMyCurrent{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsreturn"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsReturn{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmycompleted"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMyCompleted{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmydistance"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMydistance{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmyproduct"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMyProduct{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionswhattwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsWhatTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsapproval"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsapproval{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmysuccessful"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMySuccessful{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsreturnone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsReturnOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmyproducts"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMyProducts{" "}
          </Link>{" "}
        </li>
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmybanktwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMyBankTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmyheadone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMyHeadOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmydistanceone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMyDistanceOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionsmydeliveryfour"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsMydeliveryFour{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionscomment"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsComment{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionscommentone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsCommentOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myshoppingtransactionscommenttwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyShoppingTransactionsCommentTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilesellingvehiclevaluation"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileSellingVehicleValuation{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilesellingvehiclevaluationone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileSellingVehicleValuationOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilesellingvehiclesalesguide"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileSellingVehicleSalesGuide{" "}
          </Link>{" "}
        </li>
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilesellingautodictionary"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileSellingAutoDictionary{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilesellingvehiclesalesguideone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileSellingVehicleSalesGuideOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilesellingvehiclesalesguidetwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileSellingVehicleSalesGuideTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilesellingvehiclesalesguidethree"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileSellingVehicleSalesGuideThree{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilesellingvehiclesalesguidefour"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileSellingVehicleSalesGuideFour{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/whilesellingvehiclesalesguidefive"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            WhileSellingVehicleSalesGuideFive{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/autoexpertiseone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            AutoExpertiseOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountmypersonalinformation"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountMyPersonalInformation{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountmypersonalinformationone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountMyPersonalInformationOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountemail"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountEmail{" "}
          </Link>{" "}
        </li>
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountmobilephone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountMobilePhone{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountpasswordchange"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountPasswordChange{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountaccountverification"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountAccountVerification{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountaccountcancellation"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountAccountCancellation{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountsecurity2stepverification"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountSecurity2StepVerification{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountsecurityrecoveremail"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountSecurityRecoverEmail{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountsecuritysessions"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountSecuritySessions{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountmysavedcards"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountMySavedCards{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountmyaccountactivities"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountMyAccountActivities{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountaccountholders"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountAccountHolders{" "}
          </Link>{" "}
        </li>
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountmypermissionsnotification"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountMyPermissionsNotification{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountelectronicmessage"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountElectronicMessage{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/myaccountmessagereadinformation"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MyAccountMessageReadInformation{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/messagesandnotificationsmy"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MessagesandNotificationsMy{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/messagesandnotificationsinformations"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MessagesandNotificationsInformations{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/messagesandnotificationsmyone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MessagesandNotificationsMyOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/messagesandnotificationsmytwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MessagesandNotificationsMyTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/messagesandnotificationsmythree"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            MessagesandNotificationsMyThree{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/favoritesfavoritelistings"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            FavoritesFavoriteListings{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/favoritesfavoriteseaches"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            FavoritesFavoriteSeaches{" "}
          </Link>{" "}
        </li>
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/favoritesfavoritesellers"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            FavoritesFavoriteSellers{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/sahibindenrealestate360"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            SahibindenRealEstate360{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/creditone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            CreditOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateexpertise"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateExpertise{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateindex"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateIndex{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/propertybuyingguide"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            PropertyBuyingGuide{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateindexwhenselling"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateIndexWhenSelling{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateexpertisepropertyone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateExpertisePropertyOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateexpertisepropertytwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateExpertisePropertyTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestatedictionary"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateDictionary{" "}
          </Link>{" "}
        </li>
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateindexwhenrenting"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateIndexWhenRenting{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateexpertisewhenrenting"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateExpertiseWhenRenting{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestatedictionarywhenrenting"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateDictionaryWhenRenting{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateexpertisewhenrentingone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateExpertiseWhenRentingOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateexpertisewhenrentingtwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateExpertiseWhenRentingTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateexpertiseafterlease"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateExpertiseAfterLease{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateexpertiseafterleaseone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateExpertiseAfterLeaseOne{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateindex10stepsfor"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateIndex10Stepsfor{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/credittwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            CreditTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateindexwhensellingone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateIndexWhenSellingOne{" "}
          </Link>{" "}
        </li>
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateexpertisewhenselling"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateExpertiseWhenSelling{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestatedictionarywhenselling"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateDictionaryWhenSelling{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateindexwhensellingtwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateIndexWhenSellingTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateexpertiseafterleasetwo"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateExpertiseAfterLeaseTwo{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/realestateexpertiseafterleasethree"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            RealEstateExpertiseAfterLeaseThree{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/zerovehicleworld"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            ZeroVehicleWorld{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/zerovehicleworldnewvehicle"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            ZeroVehicleWorldNewVehicle{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/zerovehicleworldzerovehicle"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            ZeroVehicleWorldZeroVehicle{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/zerovehicleworldcampaignvehicles"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            ZeroVehicleWorldCampaignVehicles{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/zerovehicleworldfindanauthorized"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            ZeroVehicleWorldFindanAuthorized{" "}
          </Link>{" "}
        </li>
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/zerovehicleworldelectricvehicle"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            ZeroVehicleWorldElectricVehicle{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/services"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            Services{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            to="/servicesone"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            ServicesOne{" "}
          </Link>{" "}
        </li>{" "}
      </ul>{" "}
    </div>
  );
};
export default Home;
